### ISSUE TITLE
 unable to configure virtual network port: could not open TUN/TAP device: No such file or directory

### ISSUE THREAD

**Issue by sean--wang** [rwv/docker-zerotier-moon#1]
When i run docker logs zerotier-moon ， I found error message like ' ERROR: unable to configure virtual network port: could not open TUN/TAP device: No such file or directory',could you give me a hand for it?
'

**Comment by MeowCold** [comment]
我也遇到相同的问题 233

**Comment by rwv** [comment]
You need to run the container with the `privileged` flag or `--cap-add=NET_ADMIN` 

You could see more methods at https://www.reddit.com/r/docker/comments/4cw758/accessing_tuntap_device_inside_of_a_docker/
