### ISSUE TITLE
动态公网ip重建容器后是否可能保持moon id不变

### ISSUE THREAD

**Issue by Zailushang211** [rwv/docker-zerotier-moon#11]
由于是动态公网IP，IP改变后只能重建容器，此时使用原来的文件映射配置导致内容冲突，原来的moon id显示在线但实际上无法使用。这种情况有可能删除原来的配置内容，然后重建容器但同时保留moon id吗？否则所有终端都要重新orbit一遍，那这个moon就几乎没有意义了，如果可以保留还可以通过定期检测IP变化然后重建容器。

**Comment by rwv** [comment]
根据 zerotier 官方的说法，没办法
