### ISSUE TITLE
How to start this image if don't have fixed ip address?

### ISSUE THREAD

**Issue by lyolve** [rwv/docker-zerotier-moon#3]
```docker run --name zerotier-moon -d --restart always -p 9993:9993/udp seedgou/zerotier-moon -4 1.2.3.4```

Don't have fixed ip address.
Can this Image get my ip address automatically?

**Comment by rwv** [comment]
Sorry, ZeroTier moon does not support dynamic ip yet. 
https://github.com/zerotier/ZeroTierOne/issues/1047
