### ISSUE TITLE
Support DDNS or dynamic IP

### ISSUE THREAD

**Issue by kalavt** [rwv/docker-zerotier-moon#5]
it would be awesome to support DDNS or Dynamic IP. 
I'm aware of zerotier does not support this feature currently, 
but it can be realized by shell script watch internet IP(http://ipinfo.io/json) and reconfiguration maybe?

**Comment by rwv** [comment]
Reconfiguration will be very painful since you need update config on both server and **client** side. There’s no good way to update on the **client** side.

**Comment by kalavt** [comment]
> Reconfiguration will be very painful since you need update config on both server and **client** side. There’s no good way to update on the **client** side.

indeed, let's looking forward to version 2.0 then.
