### ISSUE TITLE
Get an fatal error if need generate moons.d 

### ISSUE THREAD

**Issue by leeaash** [rwv/docker-zerotier-moon#7]
I just try to rebuild the container after my moon's public IP address had changed.

I did delete the moon.json and moons.d folder, then ran to build the container, I got the error message `/usr/sbin/zerotier-one: fatal error: cannot bind to local control interface port 9993` and no container was created, but the new moon.json and moons.d folder were both created. I repeat the same command, the container can be created successfully

**Comment by rwv** [comment]
I would recommend to delete the whole conf folder instead of just moon-related files. Modifying moon file directly is not supported  as far as I know.
